// Generated by CoffeeScript 1.10.0
$(function() {
  var addr, adqr, btn, chars, kc, message, mex, qr_el, set_address, update_chars_count, write;
  mex = $("input[name=message]");
  chars = $(".chars_count");
  btn = $("button.main");
  qr_el = $(".qr");
  addr = $(".address a");
  adqr = $(".address a, .qr");
  message = function() {
    return mex.val();
  };
  update_chars_count = function() {
    return chars.html(message().length);
  };
  write = function(message) {
    return console.log("write " + message);
  };
  set_address = function(address) {
    var qr;
    addr.html(address);
    qr = new QRCode(qr_el.get(0), address);
    return console.log(qr);
  };
  mex.on("keyup", function() {
    console.log("keyup on input: mex (main message)");
    return update_chars_count();
  });
  btn.on("click", function() {
    return write(message());
  });
  adqr.on("click", function() {
    return qr_el.toggleClass("hidden");
  });
  kc = new KeyChain;
  console.log(kc.address_s);
  return set_address(kc.address_s);
});
