// Generated by CoffeeScript 1.10.0
$(function() {
  var adqr, btn, chars, kc, message, mex, qr, update_chars_count, write;
  mex = $("input[name=message]");
  chars = $(".chars_count");
  btn = $("button.main");
  qr = $(".qr");
  adqr = $(".address a, .qr");
  message = function() {
    return mex.val();
  };
  update_chars_count = function() {
    return chars.html(message().length);
  };
  write = function(message) {
    return console.log("write " + message);
  };
  mex.on("keyup", function() {
    console.log("keyup on input: mex (main message)");
    return update_chars_count();
  });
  btn.on("click", function() {
    return write(message());
  });
  adqr.on("click", function() {
    return qr.toggleClass("hidden");
  });
  kc = new KeyChain;
  return console.log(kc.address_s);
});
